# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.192.0/containers/ruby/.devcontainer/base.Dockerfile

# [Choice] Ruby version: 3, 3.0, 2, 2.7, 2.6
ARG VARIANT="3.0"

FROM mcr.microsoft.com/vscode/devcontainers/ruby:0-${VARIANT}